### ISSUE TITLE
我要新的 LGTM!

### ISSUE THREAD

**Issue by Origami404** [hitszosa/hitsz-osa-stickers#6]
要这一张! 

![](https://n.hopp.top/lgtm-s.svg)

_Originally posted by @h0gan1ee in https://github.com/hitszlug/wiki/pull/39#pullrequestreview-908143026_

**Comment by rewired-gh** [comment]
Head to https://n.hopp.top/lgtm-s.svg

**Comment by rewired-gh** [comment]
Uploaded.
